import '../src/styles/globals.css'
import Navbar from './components/NavBar'

export const metadata = {
  title: 'Document Manager',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
